// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb9XnhWpoWvWa3GhQ4A9edj_ei4WyzW34',
    appId: '1:91193617902:web:2b6d05dafb1f73abd672ff',
    messagingSenderId: '91193617902',
    projectId: 'fruits-hub-db083',
    authDomain: 'fruits-hub-db083.firebaseapp.com',
    storageBucket: 'fruits-hub-db083.firebasestorage.app',
    measurementId: 'G-JSRNZL1B59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzufb3l7ehHPNdGE61u8GcW4cr_B-U1nA',
    appId: '1:91193617902:android:85ad54a3ff15ec25d672ff',
    messagingSenderId: '91193617902',
    projectId: 'fruits-hub-db083',
    storageBucket: 'fruits-hub-db083.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjMzO1c5o_O6HajvcIjjt1gLKjoYEvvzY',
    appId: '1:91193617902:ios:820e84bf3409aba3d672ff',
    messagingSenderId: '91193617902',
    projectId: 'fruits-hub-db083',
    storageBucket: 'fruits-hub-db083.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb9XnhWpoWvWa3GhQ4A9edj_ei4WyzW34',
    appId: '1:91193617902:web:a10152f2a05d213fd672ff',
    messagingSenderId: '91193617902',
    projectId: 'fruits-hub-db083',
    authDomain: 'fruits-hub-db083.firebaseapp.com',
    storageBucket: 'fruits-hub-db083.firebasestorage.app',
    measurementId: 'G-YBY3CE67MD',
  );

}